export const genderColor: Record<string, any> = {
  '': 'default',
  erkak: 'primary',
  мужской: 'primary',
  женский: 'error',
  ayol: 'error',
  female: 'error',
  male: 'primary',
  erkek: 'primary',
  háyel: 'error',
};
export const gender: Record<string, any> = {
  erkak: 'Erkak',
  мужской: 'Мужской',
  женский: 'Женский',
  ayol: 'Ayol',
  female: 'Female',
  male: 'Male',
  erkek: 'Erkek',
  háyel: 'Háyel',
};

export const occupation: Record<string, any> = {
  maktab: 'Maktab',
  school: 'School',
  школа: 'Школа',
  mektep: 'Mektep',
  universitet: 'OTM',
  university: 'Unsiversty',
  университет: 'Университет',
  'kollej/texnikum': 'Kollej/texnikum',
  'college/Technikum': 'College/Technikum',
  'колледж/Техникум': 'Колледж/Техникум',
  boshqa: 'Boshqa',
  basqa: 'Basqa',
  другой: 'Другой',
  another: 'Another',
};
export const occupationColor: Record<string, any> = {
  '': 'default',
  maktab: 'warning',
  school: 'warning',
  школа: 'warning',
  mektep: 'warning',
  universitet: 'success',
  university: 'success',
  университет: 'success',
  'kollej/texnikum': 'success',
  'college/Technikum': 'success',
  'колледж/Техникум': 'success',
  boshqa: 'secondary',
  basqa: 'secondary',
  другой: 'secondary',
  another: 'secondary',
};
